### ISSUE TITLE
运行出现错误

### ISSUE THREAD

**Issue by xuchaoa** [henson/proxypool#19]
你好，运行出现如下报错
```
C:\Users\AppData\Local\Programs\Python\Python36\python.exe F:/code/ProxyPool/run.py
Traceback (most recent call last):
  File "F:/code/ProxyPool/run.py", line 1, in <module>
    from proxypool.api import app
  File "F:\code\ProxyPool\proxypool\api.py", line 1, in <module>
    from flask import Flask,g
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\flask\__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wrappers.py", line 37, in <module>
    from werkzeug.formparser import FormDataParser, default_stream_factory
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\formparser.py", line 28, in <module>
    from werkzeug.wsgi import make_line_iter, \
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\werkzeug\wsgi.py", line 13, in <module>
    import httplib
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\httplib.py", line 345
    print "reply:", repr(line)
                 ^
SyntaxError: invalid syntax

Process finished with exit code 1
```

**Comment by xuchaoa** [comment]
123
