### ISSUE TITLE
有时候会闪退？

### ISSUE THREAD

**Issue by ensyucha** [henson/proxypool#38]
报错如下图：
![error](https://user-images.githubusercontent.com/50865015/58163949-7678d300-7cb7-11e9-86b5-420334297b77.png)

**Comment by ensyucha** [comment]
2019/05/22 17:36:03 [TRACE] Log path:
2019/05/22 17:36:03 [TRACE] Log Mode: File (Info)
2019/05/22 17:36:03 [ INFO] ProxyPool
2019/05/22 17:36:03 Starting server 0.0.0.0:33333
2019/05/22 17:36:03 Chan: 0, IP: 743
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x8f6441]

goroutine 85 [running]:
github.com/Aiicy/htmlquery.(*NodeNavigator).NodeType(0xc000004b00, 0x0)
        C:/GoProject/src/github.com/Aiicy/htmlquery/query.go:145 +0x31
github.com/antchfx/xpath.axisPredicate.func1(0xc80e40, 0xc000004b00, 0x40d9ff)
        C:/GoProject/src/github.com/antchfx/xpath/build.go:45 +0x59
github.com/antchfx/xpath.(*descendantQuery).Select.func1(0xb5b840, 0xc0003d4060)
        C:/GoProject/src/github.com/antchfx/xpath/query.go:239 +0x137
github.com/antchfx/xpath.(*descendantQuery).Select(0xc0006a9c80, 0xc6d780, 0xc000004ac0, 0x418942, 0x3ea1858)
        C:/GoProject/src/github.com/antchfx/xpath/query.go:266 +0x3b
github.com/antchfx/xpath.(*filterQuery).Select(0xc000004a60, 0xc6d780, 0xc000004ac0, 0x8, 0x0)
        C:/GoProject/src/github.com/antchfx/xpath/query.go:529 +0x52
github.com/antchfx/xpath.(*descendantQuery).Select(0xc0006a9d10, 0xc6d780, 0xc000004ac0, 0x2030000, 0x30000)
        C:/GoProject/src/github.com/antchfx/xpath/query.go:229 +0xbc
github.com/antchfx/xpath.(*filterQuery).Select(0xc000004aa0, 0xc6d780, 0xc000004ac0, 0xc000357da0, 0x40d143)
        C:/GoProject/src/github.com/antchfx/xpath/query.go:529 +0x52
github.com/antchfx/xpath.(*descendantQuery).Select(0xc0006a9dd0, 0xc6d780, 0xc000004ac0, 0xc0006a9dd0, 0xc000357d98)
        C:/GoProject/src/github.com/antchfx/xpath/query.go:229 +0xbc
github.com/antchfx/xpath.(*descendantQuery).Select(0xc0003d4030, 0xc6d780, 0xc000004ac0, 0x20, 0xb324a0)
        C:/GoProject/src/github.com/antchfx/xpath/query.go:229 +0xbc
github.com/antchfx/xpath.(*NodeIterator).MoveNext(0xc000004ac0, 0xc000004ac0)
        C:/GoProject/src/github.com/antchfx/xpath/xpath.go:85 +0x50
github.com/Aiicy/htmlquery.Find(0x0, 0xbbed41, 0x39, 0xc6e080, 0xc0006a99e0, 0x0, 0x0, 0x0)
        C:/GoProject/src/github.com/Aiicy/htmlquery/query.go:32 +0x161
proxypool/getter.PLP(0x0, 0x0, 0x0)
        C:/GoProject/src/proxypool/getter/plp.go:14 +0x75
main.run.func1(0xc000050420, 0xc0002cc000, 0xbd2710)
        C:/GoProject/src/proxypool/main.go:74 +0x32
created by main.run
        C:/GoProject/src/proxypool/main.go:73 +0xf5

**Comment by sndnvaps** [comment]
这可能是plp 代理网站出问题了，无法得到相关的代理ip,注释掉main.go中的plp相关的代码，再运行测试一下吧。。 。。 
我最近在外面，没有时间看issus.
